#This SPARQL query returns all MIE - AO links based on AOPs. 
#The quoted line 11 can be unquoted to return AOs related to a selected (group of) MIE(s).
prefix aop.events: <https://identifiers.org/aop.events/>

SELECT DISTINCT ?MIE ?MolecularInitiatingEventName ?AOwebpage  ?AdverseOutcomeName WHERE { 
  #VALUES ?MIE {aop.events:1539 aop.events:1495 aop.events:1194 aop.events:1632 aop.events:1634} #Change the list to select other MIEs
  ?MIE dc:identifier ?MIELookup ; 
  dc:title ?MolecularInitiatingEventName . 
  ?AOPwebpage a aopo:AdverseOutcomePathway ; 
  aopo:has_molecular_initiating_event ?MIELookup; 
  aopo:has_adverse_outcome ?AOwebpage. 
  ?AOwebpage dc:title ?AdverseOutcomeName .
}
