#This SPARQL query allows querying all field of the AOP-Wiki RDF by regular expression

SELECT ?item ?name ?predicate ?text WHERE {
  ?item ?predicate ?text ; 
      dc:title ?name .
  FILTER regex (?text, "nanotube", "i")} #Adapt "nanotube" to perform other searches
  ORDER BY DESC (?item)
